name: Build image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USER/ibank:latest
      - name: Docker Push
        run: docker push $DOCKER_USER/ibank:latest
